name: Self-hosted runner AMD GPU (push)

on:
  push:
    branches:
      - main
      - ci-*


env:
  HF_HOME: /mnt/cache
  TRANSFORMERS_IS_CI: yes
  OMP_NUM_THREADS: 8
  MKL_NUM_THREADS: 8
  PYTEST_TIMEOUT: 60
  TF_FORCE_GPU_ALLOW_GROWTH: true
  RUN_PT_TF_CROSS_TESTS: 1"

jobs:
  check_runners:
    name: Check Runners 1 (multi-gpu) 
    runs-on: [self-hosted, docker-gpu, amd-gpu, multi-gpu, mi250]
    container:
      image: huggingface/transformers-pytorch-amd-gpu-push-ci
      options: --device /dev/kfd --device /dev/dri --shm-size "16gb" --env HIP_VISIBLE_DEVICES --env ROCR_VISIBLE_DEVICES --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    steps:
      - name: ROCM-SMI
        run: |
          rocminfo  |grep "Agent" -A 14
      - name: "show HIP env"
        run: |
          echo "Output HIP: $HIP_VISIBLE_DEVICES"
          echo "Output HIP: $ROCR_VISIBLE_DEVICES"
  check_runners2:
    name: Check Runners 2 (multi-gpu)   
    runs-on: [self-hosted, docker-gpu, amd-gpu, multi-gpu, mi250]
    container:
      image: huggingface/transformers-pytorch-amd-gpu-push-ci
      options: --device /dev/kfd --device /dev/dri --shm-size "16gb" --env HIP_VISIBLE_DEVICES --env ROCR_VISIBLE_DEVICES --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    steps:
      - name: ROCM-SMI
        run: |
          rocminfo  |grep "Agent" -A 14
      - name: "show HIP env"
        run: |
          echo "Output HIP: $HIP_VISIBLE_DEVICES"
          echo "Output ROCR: $ROCR_VISIBLE_DEVICES"
  check_runners3:
    name: Check Runners 1 (single-gpu)    
    runs-on: [self-hosted, docker-gpu, amd-gpu, single-gpu, mi250]
    container:
      image: huggingface/transformers-pytorch-amd-gpu-push-ci
      options: --device /dev/kfd --device /dev/dri --shm-size "16gb" --env HIP_VISIBLE_DEVICES --env ROCR_VISIBLE_DEVICES --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    steps:
      - name: ROCM-SMI
        run: |
          rocminfo  |grep "Agent" -A 14
      - name: "show HIP env"
        run: |
          echo "Output HIP: $HIP_VISIBLE_DEVICES"
          echo "Output ROCR: $ROCR_VISIBLE_DEVICES"
  
  check_runners4:
    name: Check Runners 2 (single-gpu)    
    runs-on: [self-hosted, docker-gpu, amd-gpu, single-gpu, mi250]
    container:
      image: huggingface/transformers-pytorch-amd-gpu-push-ci
      options: --device /dev/kfd --device /dev/dri --shm-size "16gb" --env HIP_VISIBLE_DEVICES --env ROCR_VISIBLE_DEVICES --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    steps:
      - name: ROCM-SMI
        run: |
          rocminfo  |grep "Agent" -A 14
      - name: "show HIP env"
        run: |
          echo "Output HIP: $HIP_VISIBLE_DEVICES"
          echo "Output ROCR: $ROCR_VISIBLE_DEVICES"
  
  check_runners5:
    name: Check Runners 3 (single-gpu)    
    runs-on: [self-hosted, docker-gpu, amd-gpu, single-gpu, mi250]
    container:
      image: huggingface/transformers-pytorch-amd-gpu-push-ci
      options: --device /dev/kfd --device /dev/dri --shm-size "16gb" --env HIP_VISIBLE_DEVICES --env ROCR_VISIBLE_DEVICES --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    steps:
      - name: ROCM-SMI
        run: |
          rocminfo  |grep "Agent" -A 14
      - name: "show HIP env"
        run: |
          echo "Output HIP: $HIP_VISIBLE_DEVICES"
          echo "Output ROCR: $ROCR_VISIBLE_DEVICES"
  
  check_runners6:
    name: Check Runners 4 (single-gpu)    
    runs-on: [self-hosted, docker-gpu, amd-gpu, single-gpu, mi250]
    container:
      image: huggingface/transformers-pytorch-amd-gpu-push-ci
      options: --device /dev/kfd --device /dev/dri --shm-size "16gb" --env HIP_VISIBLE_DEVICES --env ROCR_VISIBLE_DEVICES --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    steps:
      - name: ROCM-SMI
        run: |
          rocminfo  |grep "Agent" -A 14
      - name: "show HIP env"
        run: |
          echo "Output HIP: $HIP_VISIBLE_DEVICES"
          echo "Output ROCR: $ROCR_VISIBLE_DEVICES"