name: test action

on:
  push:
    branches:
      - main

jobs:
  test-job:
    name: test-job
    runs-on: [ self-hosted, hf, default ]
    steps:
      - name: echo toto
        run: echo toto