name: Self-hosted runner AMD GPU (push)

on:
  push:
    branches:
      - main
      - ci-*


env:
  HF_HOME: /mnt/cache
  TRANSFORMERS_IS_CI: yes
  OMP_NUM_THREADS: 8
  MKL_NUM_THREADS: 8
  PYTEST_TIMEOUT: 60
  TF_FORCE_GPU_ALLOW_GROWTH: true
  RUN_PT_TF_CROSS_TESTS: 1"

jobs:
  get_context:
    runs-on: [self-hosted, docker-gpu, amd-gpu, multi-amd-gpu, mi210]
    steps:
      - id: "gethip"
        run: |
          echo "Output HIP: $HIP_VISIBLE_DEVICES"
  check_runners:
    name: Check Runners    
    needs: [get_context]
    runs-on: [self-hosted, docker-gpu, amd-gpu, multi-amd-gpu, mi210]
    container:
      image: huggingface/transformers-pytorch-amd-gpu-push-ci
      options: --device /dev/kfd --device /dev/dri --shm-size "16gb" -e HIP_VISIBLE_DEVICES=$HIP_VISIBLE_DEVICES -e --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    steps:
      - name: ROCM-SMI
        run: |
          rocminfo  |grep "Agent" -A 14