name: test action

on:
  push:
    branches:
      - main

jobs:
  test-job:
    name: test-job
    runs-on: [ self-hosted, linux, x64, ubuntu-latest, 2xlarge ]
    steps:
      - name: echo toto
        run: echo toto